### ISSUE TITLE
学术交流

### ISSUE THREAD

**Issue by XinjianOUYANG** [Yangxinsix/painn-sli#2]
你好,我是西安交通大学的博士生欧阳鑫健,我目前在做MPNN用于晶体建模和大规模模拟的工作,对你的工作很感兴趣.

方便告知一下邮箱,相互交流吗?

**Comment by Yangxinsix** [comment]
你好，可以通过这个邮箱xinyang@dtu.dk或yangxin_16@outlook.com联系
